package com.jules.android.gui.data.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents a Jules session
 */
@JsonClass(generateAdapter = true)
data class Session(
    @Json(name = "name")
    val name: String,
    
    @Json(name = "prompt")
    val prompt: String? = null,
    
    @Json(name = "state")
    val state: String? = null,
    
    @Json(name = "sourceContext")
    val sourceContext: SourceContext? = null,
    
    @Json(name = "createTime")
    val createTime: String? = null,
    
    @Json(name = "updateTime")
    val updateTime: String? = null,
    
    @Json(name = "activities")
    val activities: List<Activity>? = null
)

/**
 * Source context for a session
 */
@JsonClass(generateAdapter = true)
data class SourceContext(
    @Json(name = "source")
    val source: String
)

/**
 * Create session request
 */
@JsonClass(generateAdapter = true)
data class CreateSessionRequest(
    @Json(name = "prompt")
    val prompt: String,
    
    @Json(name = "sourceContext")
    val sourceContext: SourceContext
)

/**
 * Activity within a session
 */
@JsonClass(generateAdapter = true)
data class Activity(
    @Json(name = "name")
    val name: String,
    
    @Json(name = "type")
    val type: String? = null,
    
    @Json(name = "state")
    val state: String? = null,
    
    @Json(name = "message")
    val message: String? = null,
    
    @Json(name = "plan")
    val plan: Plan? = null,
    
    @Json(name = "createTime")
    val createTime: String? = null
)

/**
 * Plan generated by Jules
 */
@JsonClass(generateAdapter = true)
data class Plan(
    @Json(name = "description")
    val description: String? = null,
    
    @Json(name = "steps")
    val steps: List<PlanStep>? = null
)

/**
 * Step in a plan
 */
@JsonClass(generateAdapter = true)
data class PlanStep(
    @Json(name = "description")
    val description: String,
    
    @Json(name = "state")
    val state: String? = null
)

/**
 * Response containing list of sessions
 */
@JsonClass(generateAdapter = true)
data class SessionsResponse(
    @Json(name = "sessions")
    val sessions: List<Session> = emptyList(),
    
    @Json(name = "nextPageToken")
    val nextPageToken: String? = null
)
